#165007339 Users should be able to sign up on the application
oleesir/banka pull request #15
Opened 2019-05-20 15:38 UTC by oleesir

#### What does this PR do?
- Implement signup-endpoint
#### Description of Task to be completed?
- Implement signup-endpoint
#### How should this be manually tested?
- Use postman to test endpoint
#### What are the relevant pivotal tracker stories?
[#165007339](https://www.pivotaltracker.com/story/show/165007339)
#### Any background context you want to add?
N/A
#### Screenshots
N/A

2019-05-20 23:31 UTC, iverenshaguy requested changes
Please update your PR description and fix all hound errors

2019-05-21 14:27 UTC, iverenshaguy requested changes
Great job, I'm impressed. Please implement my feedback or ask for more clarity if needed.

2019-05-21 14:27 UTC, iverenshaguy commented on .env
> +SECRET_KEY=mysecret
You should never commit your `.env` file because it will usually contain secret values

2019-05-21 14:27 UTC, iverenshaguy commented on .env.sample
> +SECRET_KEY=
Great job adding a sample `.env` file to guide users of your project

2019-05-21 14:27 UTC, iverenshaguy commented on .gitignore
> +.env
I see that you git ignored your `.env` file. Always ensure that an ignored file is not already committed or staged when committing your changes so that the `gitignore` will take effect

2019-05-21 14:27 UTC, iverenshaguy commented on package.json
> +   },
Please remove the space

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/Validation/Auth.validation.js
> +
This new line shouldn't be here. Also, please give your JSDoc a name.

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/Validation/Auth.validation.js
> +/**
Please leave a newline above this line

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/Validation/Auth.validation.js
> + * @class AuthValidation
Please remove the new line on line 14

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/Validation/Auth.validation.js
> +const isEmpty = value => (
I believe it would be better to move these validation helpers functions to their own utils file. All your files must also obey the Single Responsibility Principle (SRP).

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/Validation/Auth.validation.js
> +   *
Please give your JSDoc a heading

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/Validation/Auth.validation.js
> +   * @returns {object} status code and error message properties
Please leave a newline between JSDoc categories e.g between line 23 and 24. It makes it easier to read.

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/Validation/Auth.validation.js
> +export {
Please fix

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/app.js
> +import routes from './routes/index';
the `/index` isn't required because the engine will pull it in automatically when you use `./routes`

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/controllers/Auth.controller.js
> +   *@method signup
Please leave a space between * and @method. Also always leave new lines between JSDoc categories to aid readability

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/controllers/Auth.controller.js
> +    newUser.password = password.trim();
I can't see that we are encrypting this password. Is that the case?

2019-05-21 14:27 UTC, iverenshaguy commented on server/src/middlewares/asyncErrorHandler.js
> +const asyncErrorHandler = fn => (req, res, next) => Promise.resolve(fn(req, res, next)).catch(next);
Do you understand this implementation?

2019-05-22 10:43 UTC, oleesir commented on .env
> +SECRET_KEY=mysecret
done

2019-05-22 10:44 UTC, oleesir commented on .env.sample
> +SECRET_KEY=
thanks

2019-05-22 10:44 UTC, oleesir commented on .gitignore
> +.env
noted

2019-05-22 20:01 UTC, ishaguy-coursera submitted a review, later dismissed
Good job

2019-05-22 20:02 UTC, iverenshaguy submitted a review, later dismissed
Good job

2019-05-23 10:27 UTC, iverenshaguy approved these changes
Great job. Well done

2019-05-23 10:28 UTC, merged